# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build & deploy notes.vyckey.github.io to GitHub Pages

on:
  push:
    branches: [ "main", "test"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Packages
      run: rm -rf node_modules && npm ci --legacy-peer-deps
    - name: Build
      run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: vyckey-computer-notes